# Generated by Django 4.2.13 on 2024-05-30 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_author_alter_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
    ]
