# Generated by Django 4.2.13 on 2024-05-30 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='conclusion',
        ),
        migrations.RemoveField(
            model_name='post',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='post',
            name='quoter',
        ),
    ]
